GET http://localhost:8080/exam/java/add?question=QuestionText&answer=QuestionAnswer
###
GET http://localhost:8080/exam/java/add?question=QuestionText1&answer=QuestionAnswer1
###
GET http://localhost:8080/exam/java/add?question=QuestionText7
###
GET http://localhost:8080/exam/java/add?question=QuestionText3&answer=QuestionAnswer3
###
GET http://localhost:8080/exam/java/add?question=QuestionText4&answer=QuestionAnswer4
###
GET http://localhost:8080/exam/java/add?question=QuestionText5&answer=QuestionAnswer5
###
GET http://localhost:8080/exam/java
###
GET http://localhost:8080/exam/java/remove?question=QuestionText1&answer=QuestionAnswer1
###
GET http://localhost:8080/exam/java
###
GET http://localhost:8080/exam/get/3
###
GET http://localhost:8080/exam/get/6